#- name: Upload coverage reports to Codecov
#  uses: codecov/codecov-action@v3
#    env: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


name: Upload coverage reports to Codecov

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install 
      - name: Run tests
        run: npm run codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}